apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: smailandstuff
spec:
  build:
    #secrets:
    #  - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "e736905f-5aed-443d-a693-867c62833e5d"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET